linux_test_task:
  container:
    image: ghcr.io/flipstone/haskell-tools:debian-unstable-ghc-9.4.5-2023-07-18-1d8bf61
    cpu: 6
    memory: 6G
  stack_cache:
    # Note how this is so wildly different than other platforms..
    folder: /stack-root
  install_script:
    - apt update
    - apt install bmake
    - bmake setup
  test_script:
    - bmake

freebsd_test_task:
  freebsd_instance:
    image_family: freebsd-13-2
    cpu: 6
    memory: 6G
  stack_cache:
    folder: ~/.stack
  install_script:
    - pkg install -y hs-stack
    - make setup
  test_script:
    - make

macos_test_task:
  macos_instance:
    image: ventura-base
    cpu: 6
    memory: 6G
  stack_cache:
    folder: ~/.stack
  install_script:
    - brew install haskell-stack bmake
    - bmake setup
  test_script:
    - bmake
